# Generated by Django 3.1.6 on 2021-02-06 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_delete_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_year',
            field=models.IntegerField(default=2019, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)]),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('subject', 'exam_year')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'exam_type')},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='exam_year',
        ),
    ]
