# Generated by Django 3.1.6 on 2021-02-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20210206_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['exam_year']},
        ),
    ]
