# Generated by Django 3.1.6 on 2021-02-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20210209_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Please an answer is required!'),
        ),
    ]
