# Generated by Django 3.1.6 on 2021-02-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_auto_20210213_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instruction',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
